[build]
builder = "NIXPACKS"
buildCommand = "npm --prefix backend install"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm --prefix backend start"
healthcheckPath = "/api/health"
sleepApplication = false
useLegacyStacker = false
ipv6EgressEnabled = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig.europe-west4-drams3a]
numReplicas = 1
